name: Docker Publish and PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/flask-app:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/flask-app:latest

  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure PyPI publish runs after Docker publish job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use your required Python version

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
           pip install poetry

      # Step 4: Install dependencies with Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Build the package with Poetry
      - name: Build the package
        run: |
          poetry build

      # Step 6: Publish to PyPI using Poetry
      - name: Publish to PyPI
        run: |
          poetry publish --username __token__ --password $env:PYPI_API_TOKEN
